// CONSTITUTION: v6.0 Final — Contradiction Engine Enums
// Engine: v5.3.1c | Seal: VO-CE-v531c-DIGSIM-20260713
// 43 contradiction types | 37 detectors | 17 serial patterns | 7 cases | B1-B11

/** 43 contradiction types detected by the v5.3.1c engine. */
export const ContradictionType = {
  // === v5.2.9 Legacy (16 types) ===
  STATEMENT_VS_STATEMENT: "STATEMENT_VS_STATEMENT",
  STATEMENT_VS_EVIDENCE: "STATEMENT_VS_EVIDENCE",
  OMISSION: "OMISSION",
  BEHAVIORAL: "BEHAVIORAL",
  FINANCIAL_IRREGULARITY: "FINANCIAL_IRREGULARITY",
  JUDICIAL_VS_DOCUMENTARY: "JUDICIAL_VS_DOCUMENTARY",
  TEMPORAL_CONTRADICTION: "TEMPORAL_CONTRADICTION",
  CONSCIOUSNESS_OF_GUILT: "CONSCIOUSNESS_OF_GUILT",
  PERJURY_BY_TIMELINE: "PERJURY_BY_TIMELINE",
  PATTERN_OF_RACKETEERING: "PATTERN_OF_RACKETEERING",
  REGULATORY_CAPTURE: "REGULATORY_CAPTURE",
  SHAM_TRANSACTION: "SHAM_TRANSACTION",
  FRAUD_ON_THE_COURT: "FRAUD_ON_THE_COURT",
  CORPORATE_VEIL_ABUSE: "CORPORATE_VEIL_ABUSE",
  TACIT_LEASE_VIOLATION: "TACIT_LEASE_VIOLATION",
  POST_EXPIRY_ENFORCEMENT: "POST_EXPIRY_ENFORCEMENT",

  // === v5.3.0 Expansion (14 types) ===
  DOCUMENT_TAMPERING: "DOCUMENT_TAMPERING",
  WITNESS_INTIMIDATION: "WITNESS_INTIMIDATION",
  EVIDENCE_DESTRUCTION: "EVIDENCE_DESTRUCTION",
  CONFLICT_OF_INTEREST: "CONFLICT_OF_INTEREST",
  BRIBERY_CORRUPTION: "BRIBERY_CORRUPTION",
  MONEY_LAUNDERING: "MONEY_LAUNDERING",
  IDENTITY_FRAUD: "IDENTITY_FRAUD",
  FORGERY: "FORGERY",
  EXTORTION: "EXTORTION",
  EMBEZZLEMENT: "EMBEZZLEMENT",
  TAX_EVASION: "TAX_EVASION",
  INSIDER_TRADING: "INSIDER_TRADING",
  CYBERCRIME_EVIDENCE: "CYBERCRIME_EVIDENCE",
  HUMAN_RIGHTS_VIOLATION: "HUMAN_RIGHTS_VIOLATION",

  // === v5.3.1 Expansion (7 types) ===
  MANDATE_ABANDONMENT: "MANDATE_ABANDONMENT",
  ACKNOWLEDGE_THEN_DENY: "ACKNOWLEDGE_THEN_DENY",
  OWNERSHIP_MISREPRESENTATION: "OWNERSHIP_MISREPRESENTATION",
  COSTING_MANIPULATION: "COSTING_MANIPULATION",
  COMMUNITY_MANIPULATION: "COMMUNITY_MANIPULATION",
  INSTITUTIONAL_SILENCE: "INSTITUTIONAL_SILENCE",
  ICCPR_REMEDY_DENIAL: "ICCPR_REMEDY_DENIAL",

  // === v5.3.1c DIGSIM Expansion (6 types) ===
  DEFECTIVE_JURAT: "DEFECTIVE_JURAT",
  PROTECTION_ORDER_AS_LEVERAGE: "PROTECTION_ORDER_AS_LEVERAGE",
  FALSE_ALLEGATION_IN_AFFIDAVIT: "FALSE_ALLEGATION_IN_AFFIDAVIT",
  TEMPORAL_PRECEDENCE_CONFLICT: "TEMPORAL_PRECEDENCE_CONFLICT",
  PROCESS_REMEDY_CONFLICT: "PROCESS_REMEDY_CONFLICT",
  CHARACTER_ASSASSINATION: "CHARACTER_ASSASSINATION",
} as const;
export type ContradictionType = (typeof ContradictionType)[keyof typeof ContradictionType];

/** 17 serial fraud patterns detected by the engine. */
export const SerialFraudPattern = {
  P001_GOODWILL_FORFEITURE: "P001_GOODWILL_FORFEITURE",
  P002_RENT_WHILE_DENYING_CONTRACT: "P002_RENT_WHILE_DENYING_CONTRACT",
  P003_UNSIGNED_DOCUMENT_ENFORCEMENT: "P003_UNSIGNED_DOCUMENT_ENFORCEMENT",
  P004_SECTION_12B_ARBITRATION_AVOIDANCE: "P004_SECTION_12B_ARBITRATION_AVOIDANCE",
  P005_COMPENSATION_DEMAND_WITHOUT_RIGHT: "P005_COMPENSATION_DEMAND_WITHOUT_RIGHT",
  P006_DUAL_CONTROL_SHAM: "P006_DUAL_CONTROL_SHAM",
  P007_JUDICIAL_PERJURY_PATTERN: "P007_JUDICIAL_PERJURY_PATTERN",
  P008_CROSS_BORDER_OPPRESSION: "P008_CROSS_BORDER_OPPRESSION",
  P009_FRANCHISE_SYSTEMATIC_EVICT: "P009_FRANCHISE_SYSTEMATIC_EVICT",
  P010_EXCLUSIVITY_DENIAL_PATTERN: "P010_EXCLUSIVITY_DENIAL_PATTERN",
  P011_GASLIGHTING_ISOLATION: "P011_GASLIGHTING_ISOLATION",
  P012_DIGITAL_EVIDENCE_TAMPERING: "P012_DIGITAL_EVIDENCE_TAMPERING",
  P013_BANKING_FRAUD_PATTERN: "P013_BANKING_FRAUD_PATTERN",
  P014_LAW_ENFORCEMENT_INTERFERENCE: "P014_LAW_ENFORCEMENT_INTERFERENCE",
  P015_DEFECTIVE_JURAT: "P015_DEFECTIVE_JURAT",
  P016_PROTECTION_ORDER_LEVERAGE: "P016_PROTECTION_ORDER_LEVERAGE",
  P017_PROCESS_REMEDY_DENIAL: "P017_PROCESS_REMEDY_DENIAL",
} as const;
export type SerialFraudPattern = (typeof SerialFraudPattern)[keyof typeof SerialFraudPattern];

/** Ordinal severity — no percentages, ever (Constitution v6.0 Final Directive 1). */
export const Severity = {
  VERY_HIGH: "VERY_HIGH",
  HIGH: "HIGH",
  MODERATE: "MODERATE",
  LOW: "LOW",
  INSUFFICIENT: "INSUFFICIENT",
} as const;
export type Severity = (typeof Severity)[keyof typeof Severity];

/** Confidence levels — DETERMINISTIC is highest (mathematical proof). */
export const Confidence = {
  DETERMINISTIC: "DETERMINISTIC",
  VERY_HIGH: "VERY_HIGH",
  HIGH: "HIGH",
  MODERATE: "MODERATE",
  LOW: "LOW",
  INSUFFICIENT: "INSUFFICIENT",
} as const;
export type Confidence = (typeof Confidence)[keyof typeof Confidence];

/** Statement types for evidence classification. */
export const StatementType = {
  CLAIM: "CLAIM",
  DENIAL: "DENIAL",
  ADMISSION: "ADMISSION",
  DEMAND: "DEMAND",
  PROMISE: "PROMISE",
  THREAT: "THREAT",
  SWORN_STATEMENT: "SWORN_STATEMENT",
  CONTEMPORANEOUS: "CONTEMPORANEOUS",
  JUDICIAL_RECORD: "JUDICIAL_RECORD",
  CONTRACT_CLAUSE: "CONTRACT_CLAUSE",
} as const;
export type StatementType = (typeof StatementType)[keyof typeof StatementType];

/** The 7 constitutional subjects + RACKETERING + OTHER. */
export const Subject = {
  GOODWILL_VALUE: "GOODWILL_VALUE",
  CONTRACT_VALIDITY: "CONTRACT_VALIDITY",
  SIGNATURE_STATUS: "SIGNATURE_STATUS",
  SECTION_12B: "SECTION_12B",
  COMPENSATION: "COMPENSATION",
  PERJURY: "PERJURY",
  COERCION: "COERCION",
  RACKETEERING: "RACKETEERING",
  OTHER: "OTHER",
} as const;
export type Subject = (typeof Subject)[keyof typeof Subject];

/** File types supported for evidence ingestion. */
export const FileType = {
  PDF: "PDF",
  IMAGE: "IMAGE",
  AUDIO: "AUDIO",
  EMAIL: "EMAIL",
  CHAT_LOG: "CHAT_LOG",
  ZIP: "ZIP",
  DOCX: "DOCX",
  XLSX: "XLSX",
  TXT: "TXT",
  CSV: "CSV",
  UNKNOWN: "UNKNOWN",
} as const;
export type FileType = (typeof FileType)[keyof typeof FileType];

/** 11 Brain identifiers (B1-B11). */
export const Brain = {
  B1_CONTRADICTION: "B1_CONTRADICTION",
  B2_DOCUMENT: "B2_DOCUMENT",
  B3_COMMUNICATIONS: "B3_COMMUNICATIONS",
  B4_BEHAVIORAL: "B4_BEHAVIORAL",
  B5_TIMELINE: "B5_TIMELINE",
  B6_FINANCIAL: "B6_FINANCIAL",
  B7_LEGAL: "B7_LEGAL",
  B8_AUDIO: "B8_AUDIO",
  B9_RESEARCH: "B9_RESEARCH",
  B10_HUMAN_RIGHTS: "B10_HUMAN_RIGHTS",
  B11_INSTITUTIONAL: "B11_INSTITUTIONAL",
} as const;
export type Brain = (typeof Brain)[keyof typeof Brain];

/** Score conversion utilities — internal use only, never exposed as confidence. */
export function severityScore(sev: Severity): number {
  return {
    [Severity.VERY_HIGH]: 5,
    [Severity.HIGH]: 4,
    [Severity.MODERATE]: 3,
    [Severity.LOW]: 2,
    [Severity.INSUFFICIENT]: 1,
  }[sev] ?? 0;
}

export function confidenceScore(c: Confidence): number {
  return {
    [Confidence.DETERMINISTIC]: 1.0,
    [Confidence.VERY_HIGH]: 0.9,
    [Confidence.HIGH]: 0.75,
    [Confidence.MODERATE]: 0.5,
    [Confidence.LOW]: 0.25,
    [Confidence.INSUFFICIENT]: 0.0,
  }[c] ?? 0.5;
}

export function scoreToConfidence(s: number): Confidence {
  if (s >= 0.95) return Confidence.DETERMINISTIC;
  if (s >= 0.80) return Confidence.VERY_HIGH;
  if (s >= 0.60) return Confidence.HIGH;
  if (s >= 0.35) return Confidence.MODERATE;
  if (s >= 0.15) return Confidence.LOW;
  return Confidence.INSUFFICIENT;
}
