import { writeFileSync, mkdirSync, existsSync } from "node:fs";
import { join } from "node:path";
import nodemailer, { type Transporter } from "nodemailer";
import type {
  CommissionInvoice,
  FirewallConfig,
  FraudAlert,
  SealRecord,
} from "../core/types.js";
import { assertInvoicePrivacy } from "../core/commission.js";

export interface OutboundEmail {
  to: string;
  subject: string;
  body: string;
  /** Attachments allowed ONLY for bank recipients — never for Verum */
  attachments: Array<{ filename: string; path: string }>;
  recipient_role: "verum" | "bank";
}

export interface DispatchResult {
  queued_path: string;
  delivered: boolean;
  transport: "smtp" | "queued";
  message_id?: string;
  error?: string;
}

/**
 * Notification system with CODE-enforced privacy:
 * Verum emails physically cannot attach evidence files.
 */
export class NotificationService {
  private transporter: Transporter | null = null;

  constructor(private readonly config: FirewallConfig) {}

  private smtp() {
    return this.config.email?.smtp;
  }

  private getTransporter(): Transporter | null {
    const smtp = this.smtp();
    if (!smtp?.host) return null;
    if (!this.transporter) {
      const secure = smtp.secure ?? false;
      this.transporter = nodemailer.createTransport({
        host: smtp.host,
        port: smtp.port,
        secure,
        // Enforce STARTTLS on non-secure ports unless explicitly disabled.
        requireTLS: smtp.requireTLS ?? !secure,
        auth: smtp.user ? { user: smtp.user, pass: smtp.pass } : undefined,
      });
    }
    return this.transporter;
  }

  buildVerumCommissionEmail(invoice: CommissionInvoice): OutboundEmail {
    assertInvoicePrivacy(invoice);
    const subject = `[FRAUD-COMMISSION] ${invoice.institution} -- ${invoice.case_reference} -- ${invoice.currency}${invoice.commission_amount}`;
    const body = [
      "VERUM OMNIS FRAUD COMMISSION INVOICE",
      "=====================================",
      `Institution:     ${invoice.institution}`,
      `Case Reference:  ${invoice.case_reference}`,
      `Fraud Amount:    ${invoice.currency} ${invoice.fraud_amount}`,
      `Verum Omnis 20%: ${invoice.currency} ${invoice.commission_amount}`,
      `Seal ID:         ${invoice.seal_id}`,
      `Blockchain:      Block ${invoice.blockchain_block ?? "pending"}`,
      `Date Detected:   ${invoice.generated_at}`,
      "",
      `PAYMENT DUE: ${invoice.currency} ${invoice.commission_amount}`,
      `Payment Reference: ${invoice.payment_reference}`,
      "",
      "This invoice is automatically generated when the Fraud Firewall",
      "detects confirmed fraud at a licensed institution. The sealed",
      "evidence remains with the institution. Verum Omnis does not",
      "receive customer data, transaction details, or private evidence.",
      "",
      `Verify seal: ${this.config.verum.verify_url}`,
    ].join("\n");

    const email: OutboundEmail = {
      to: this.config.verum.commission_email,
      subject,
      body,
      attachments: [], // HARD-CODED: never attach evidence to Verum
      recipient_role: "verum",
    };
    this.enforceNoEvidenceToVerum(email);
    return email;
  }

  buildBankEvidenceEmail(params: {
    alert: FraudAlert;
    seal: SealRecord;
    sealedPdfPath: string;
  }): OutboundEmail {
    const { alert, seal, sealedPdfPath } = params;
    const subject = `[FRAUD-DETECTED] ${alert.case_reference} -- Sealed Evidence Report`;
    const body = [
      "VERUM OMNIS FRAUD DETECTION REPORT",
      "==================================",
      `Institution:     ${alert.institution}`,
      `Case Reference:  ${alert.case_reference}`,
      `Fraud Amount:    ${alert.currency} ${alert.fraud_amount}`,
      `Seal ID:         ${seal.seal_id}`,
      `Blockchain:      Block ${seal.blockchain?.block_height ?? "pending"}`,
      "Status:          VERIFIED",
      "",
      `ATTACHED: Sealed forensic evidence report (${sealedPdfPath})`,
      "- SHA-512 verified",
      "- Bitcoin blockchain anchored",
      "- Court-admissible under Daubert Standard",
      "",
      "ACTION REQUIRED:",
      "The bank's fraud department should review the attached sealed",
      "evidence and determine appropriate action.",
      "",
      "This report was generated by the Verum Omnis Fraud Firewall",
      `under Constitution v${this.config.constitution_version}. Triple-AI verification confirmed.`,
    ].join("\n");

    return {
      to: this.config.institution.fraud_department_email,
      subject,
      body,
      attachments: [
        {
          filename: `sealed-evidence-${seal.seal_id}.PDF`,
          path: sealedPdfPath,
        },
      ],
      recipient_role: "bank",
    };
  }

  /**
   * Deliver an outbound email. Always writes a queued JSON audit record; when
   * SMTP is configured, also sends via SMTP. Verum emails can never carry
   * evidence attachments (code-enforced).
   */
  async dispatch(email: OutboundEmail): Promise<DispatchResult> {
    if (email.recipient_role === "verum") {
      this.enforceNoEvidenceToVerum(email);
    }
    const outDir = join(this.config.storage.vault_dir, "outbound-email");
    if (!existsSync(outDir)) mkdirSync(outDir, { recursive: true });
    const safe = email.subject.replace(/[^a-zA-Z0-9._-]+/g, "_").slice(0, 80);
    const path = join(outDir, `${Date.now()}-${email.recipient_role}-${safe}.json`);
    writeFileSync(path, JSON.stringify(email, null, 2) + "\n", "utf8");

    const transporter = this.getTransporter();
    if (!transporter) {
      return { queued_path: path, delivered: false, transport: "queued" };
    }

    // Attachments are permitted for banks only; existing files only.
    const attachments =
      email.recipient_role === "bank"
        ? email.attachments
            .filter((a) => existsSync(a.path))
            .map((a) => ({ filename: a.filename, path: a.path }))
        : [];
    try {
      const info = await transporter.sendMail({
        from: this.config.email?.from ?? "verum-omnis@localhost",
        to: email.to,
        subject: email.subject,
        text: email.body,
        attachments,
      });
      return {
        queued_path: path,
        delivered: true,
        transport: "smtp",
        message_id: (info as { messageId?: string }).messageId,
      };
    } catch (err) {
      return {
        queued_path: path,
        delivered: false,
        transport: "smtp",
        error: err instanceof Error ? err.message : String(err),
      };
    }
  }

  /**
   * CODE enforcement — not AI. Verum emails cannot carry evidence attachments.
   */
  enforceNoEvidenceToVerum(email: OutboundEmail): void {
    if (email.recipient_role !== "verum") return;
    if (email.attachments.length > 0) {
      throw new Error(
        "PRIVACY VIOLATION: Verum Omnis emails cannot attach evidence files",
      );
    }
    const lowered = `${email.subject}\n${email.body}`.toLowerCase();
    const bannedSnippets = [
      "account number",
      "customer name",
      "id number",
      "passport",
      "attachment: sealed",
    ];
    for (const snippet of bannedSnippets) {
      if (lowered.includes(snippet)) {
        throw new Error(
          `PRIVACY VIOLATION: Verum email contains forbidden content: ${snippet}`,
        );
      }
    }
  }
}
